# Example values for backwards compatibility with legacy domainName/name
# This demonstrates that existing configurations continue to work

# Basic application configuration
applicationName: "legacy-app"
containerImage:
  repository: "nginx"
  tag: "latest"

# Service configuration
service:
  enabled: true
  type: NodePort
  ports:
    app:
      port: 80
      targetPort: 80
      protocol: TCP

# Ingress configuration
ingress:
  enabled: true
  path: /
  servicePort: 80
  hosts:
    - "api.example.com"

# Google Managed Certificate with legacy single certificate (still works!)
google:
  managedCertificate:
    enabled: true
    # Legacy way - still fully supported
    domainName: "api.example.com"
    name: "legacy-cert" 